import { SpinBox, ComboBox, Button, ScrollView, Slider, StandardListView, HorizontalBox, RadioGroup } from "std-widgets.slint";
import { BatteryIndicator } from "battery-indicator.slint";
import { ImageButton } from "image-button.slint";
import { TextButton } from "text-button.slint";
import "../resources/fonts/SF-Pro-Rounded-Regular.otf";

export enum SmartGlassesScanTaskCommand {
    start,
    stop
}

export enum SmartGlassesScanTaskState {
    running,
    stopped
}

export enum RemoteIdScanTaskCommand {
    start,
    stop
}

export enum RemoteIdScanTaskState {
    running,
    stopped
}

enum SettingsView {
    none,
    date,
    timezone,
    time,
    screen,
    scan-duration
}

export component MainWindow inherits Window {
    out property <bool> showing-settings: false;
    out property <bool> showing-flashlight: false;
    in property <bool> remote-id-detected: false;
    in property <bool> smart-glasses-detected: false;
    in property <RemoteIdScanTaskState> remote-id-scan-task-state: RemoteIdScanTaskState.stopped;
    in property <SmartGlassesScanTaskState> smart-glasses-scan-task-state: SmartGlassesScanTaskState.stopped;

    pure callback set-date(month: int, day: int, year: int);
    callback get-date() -> [int]; // Day, month, years
    pure callback set-time(hour: int, minute: int, second: int);
    callback get-time() -> [int]; // Hour, minute, second
    pure callback set-timezone-offset(offset: int);
    callback get-timezone-offset() -> int;
    callback get-days-in-year-month(year: int, month: int) -> int;
    pure callback set-screen-brightness(brightness: int);
    callback get-screen-brightness() -> int;
    pure callback set-screen-timeout(timeout: int);
    callback get-screen-timeout() -> int;
    pure callback set-smart-glasses-scan-duration(duration: int);
    callback get-smart-glasses-scan-duration() -> int;
    pure callback set-remote-id-scan-duration(duration: int);
    callback get-remote-id-scan-duration() -> int;
    pure callback set-remote-id-scan-task-command(command: RemoteIdScanTaskCommand);
    pure callback set-smart-glasses-scan-task-command(command: SmartGlassesScanTaskCommand);
    callback update-datetime(hour: int, minute: int, second: int, day: int, month: int, year: int, day-of-week: int);
    callback update-battery-status(percent-charged: int, is-charging: bool);
    pure callback set-flashlight-on(bool);

    update-datetime(hour, minute, second, day, month, year, day-of-week) => {
        watch-view.hour = hour;
        watch-view.minute = minute;
        watch-view.second = second;
        watch-view.day = day;
        watch-view.month = month;
        watch-view.year = year;
        watch-view.day-of-week = day-of-week;
    }

    update-battery-status(percent-charged, is-charging) => {
        battery-indicator.value = percent-charged;
        battery-indicator.charging = is-charging;
    }

    width: 410px;
    height: 502px;
    background: black;
    default-font-family: "SF Pro Rounded";
    default-font-size: 32px;

    watch-view := SwipeGestureHandler {
        property <int> hour: 0;
        property <int> minute: 0;
        property <int> second: 0;
        property <int> day: 0;
        property <int> month: 0;
        property <int> year: 0;
        property <int> day-of-week: 0;
        
        VerticalLayout {
            Rectangle {
                HorizontalLayout {
                    ImageButton {
                        icon: @image-url("../resources/icons/material-symbols--speed-camera-outline-rounded.png");
                        icon-size: 64px;
                    }
                    ImageButton {
                        icon: @image-url("../resources/icons/material-symbols--eyeglasses-2-rounded.png");
                        icon-size: 64px;

                        clicked => {
                            root.set-smart-glasses-scan-task-command(root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.stopped ? SmartGlassesScanTaskCommand.start : SmartGlassesScanTaskCommand.stop);
                        }

                        states [
                            detected when root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.running  && root.smart-glasses-detected: {
                                activated: true;
                            }
                            running when root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.running && !root.smart-glasses-detected: {
                                running: true;
                            }
                        ]
                    }
                    Rectangle {
                        height: parent.height / 3;
                    }
                    ImageButton {
                        icon: @image-url("../resources/icons/material-symbols--drone-outline-rounded.png");
                        icon-size: 64px;

                        clicked => {
                            root.set-remote-id-scan-task-command(root.remote-id-scan-task-state == RemoteIdScanTaskState.stopped ? RemoteIdScanTaskCommand.start : RemoteIdScanTaskCommand.stop);
                        }

                        states [
                            detected when root.remote-id-scan-task-state == RemoteIdScanTaskState.running  && root.remote-id-detected: {
                                activated: true;
                            }
                            running when root.remote-id-scan-task-state == RemoteIdScanTaskState.running && !root.remote-id-detected: {
                                running: true;
                            }
                        ]
                    }

                    padding: 32px;
                }
                
                height: parent.height / 3;
            }
            Rectangle {
                VerticalLayout {
                    Text {
                        text: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][day-of-week];
                        color: white;
                        font-size: 32px;
                        vertical-alignment: bottom;
                        horizontal-alignment: center;
                    }
                    HorizontalLayout {
                        Rectangle {}
                        Text {
                            text: (hour < 10 ? "0" : "") + hour;
                            color: white;
                            font-size: 72px;
                            font-weight: FontWeight.black;
                            vertical-alignment: bottom;
                            horizontal-alignment: right;
                            width: 90px;
                        }
                        Text {
                            text: ":";
                            color: white;
                            font-size: 72px;
                            font-weight: FontWeight.black;
                            vertical-alignment: bottom;
                            horizontal-alignment: center;
                        }
                        Text {
                            text: (minute < 10 ? "0" : "") + minute;
                            color: white;
                            font-size: 72px;
                            font-weight: FontWeight.black;
                            vertical-alignment: bottom;
                            horizontal-alignment: center;
                            width: 88px;
                        }
                        Text {
                            text: ":";
                            color: white;
                            font-size: 72px;
                            font-weight: FontWeight.black;
                            vertical-alignment: bottom;
                            horizontal-alignment: center;
                        }
                        Text {
                            text: (second < 10 ? "0" : "") + second;
                            color: white;
                            font-size: 72px;
                            font-weight: FontWeight.black;
                            vertical-alignment: bottom;
                            horizontal-alignment: left;
                            width: 88px;
                        }
                        Rectangle {}
                    }
                    Text {
                        text: (month < 10 ? "0" : "") + month + "-" + (day < 10 ? "0" : "") + day + "-" + (year < 10 ? "0" : "") + year;
                        color: white;
                        font-size: 32px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                }

                height: parent.height / 3;
            }
            battery-indicator := BatteryIndicator {
                icon-size: 64px;
            }
        }

        swiped => {
            if self.current-position.x > self.pressed-position.x + self.width / 4 {
                showing-flashlight = true;
            } else if self.current-position.x < self.pressed-position.x - self.width / 4 {
                showing-settings = true;
            }
        }

        handle-swipe-right: true;
        handle-swipe-left: true;
        visible: !root.showing-settings;
    }

    if showing-flashlight : Rectangle {
        init => {
            root.set-flashlight-on(true);
        }

        SwipeGestureHandler {
            Rectangle {
                background: white;
            }

            swiped => {
                showing-flashlight = false;

                root.set-flashlight-on(false);
            }

            handle-swipe-left: true;
        }
    }

    if showing-settings : settings-container := Rectangle {
        property <SettingsView> showing-settings-view: SettingsView.none;

        settings-view := VerticalLayout {
            SwipeGestureHandler {
                Flickable {
                    VerticalLayout {
                        TextButton { height: 96px; text: "Date"; 
                            clicked => { showing-settings-view = SettingsView.date; }
                        }
                        TextButton {
                            height: 96px; text: "Time";
                            clicked => { showing-settings-view = SettingsView.time; }
                        }
                        TextButton {
                            height: 96px; text: "Timezone";
                            clicked => { showing-settings-view = SettingsView.timezone; }
                        }
                        TextButton {
                            height: 96px; text: "Screen";
                            clicked => { showing-settings-view = SettingsView.screen; }
                        }
                        TextButton {
                            height: 96px; text: "Scan Duration";
                            clicked => { showing-settings-view = SettingsView.scan-duration; }
                        }
                    }
                }
                swiped => {
                    root.showing-settings = false;
                }

                handle-swipe-right: true;
            }

            visible: root.showing-settings;
        }

        if showing-settings-view == SettingsView.date : Rectangle {
            function update-days-in-month(year: int, month: int) {
                day-slider.maximum = root.get-days-in-year-month(year, month);

                if day-slider.value > day-slider.maximum { day-slider.value = day-slider.maximum };
            }

            init => {
                let date = root.get-date();

                day-slider.value = date[0];
                month-slider.value = date[1];
                year-slider.value = date[2];
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Date";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text { text: "Year"; color: white; }
                        Text {
                            text: round(year-slider.value);
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    year-slider := Slider{
                        value: 2025;
                        minimum: 2025;
                        maximum: 2050;

                        changed(_) => {
                            update-days-in-month(year-slider.value, month-slider.value);
                        }
                    }
                    HorizontalLayout {
                        Text { text: "Month"; color: white; }
                        Text {
                            text: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][month-slider.value -1];
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    month-slider := Slider{
                        value: 1;
                        minimum: 1;
                        maximum: 12;

                        changed(_) => {
                            update-days-in-month(round(year-slider.value), round(month-slider.value));
                        }
                    }
                    HorizontalLayout {
                        Text { text: "Day"; color: white; }
                        Text {
                            text: round(day-slider.value);
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    day-slider := Slider{
                        value: 1;
                        minimum: 1;
                        maximum: 30;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-date(round(month-slider.value), round(day-slider.value), round(year-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.timezone : Rectangle {
            init => {
                timezone-slider.value = root.get-timezone-offset();
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Timezone";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text { text: "Offset"; color: white; }
                        Text {
                            text: round(timezone-slider.value);
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    timezone-slider := Slider{
                        value: 0;
                        minimum: -23;
                        maximum: 23;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-timezone-offset(round(timezone-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }

        if showing-settings-view == SettingsView.time : Rectangle {
            init => {
                let time = root.get-time();

                hour-slider.value = time[0];
                minute-slider.value = time[1];
                second-slider.value = time[2];
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Time";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text { text: "Hour"; color: white; }
                        Text {
                            text: round(hour-slider.value);
                            color: white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    hour-slider := Slider {
                        value: 0;
                        minimum: 0;
                        maximum: 23;
                    }
                    HorizontalLayout {
                        Text { text: "Minute"; color: white; }
                        Text {
                            text: round(minute-slider.value);
                            color: white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    minute-slider := Slider {
                        value: 0;
                        minimum: 0;
                        maximum: 59;
                    }
                    HorizontalLayout {
                        Text { text: "Second"; color: white; }
                        Text {
                            text: round(second-slider.value);
                            color: white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    second-slider := Slider {
                        value: 0;
                        minimum: 0;
                        maximum: 59;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-time(round(hour-slider.value), round(minute-slider.value), round(second-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.screen : Rectangle {
            init => {
                brightness-slider.value = root.get-screen-brightness() / (256 + 64) * 125;
                timeout-slider.value = root.get-screen-timeout() / 10;
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Screen";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text { text: "Brightness"; color: white; }
                        Text {
                            text: round(brightness-slider.value) + "%";
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    brightness-slider := Slider{
                        value: 50;
                        minimum: 1;
                        maximum: 100;

                        changed(value) => {
                            self.value = round(value/10.0) * 10;
                        }
                    }
                    HorizontalLayout {
                        Text { text: "Timeout"; color: white; }
                        Text {
                            text: timeout-slider.value > 0 ? round(timeout-slider.value) + " secs" : "Indefinite";
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    timeout-slider := Slider{
                        value: 15;
                        minimum: 0;
                        maximum: 60;

                        changed(value) => {
                            self.value = round(value/15.0) * 15;
                        }
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-screen-brightness(round(brightness-slider.value) * 0.0075 * 256 + 64);
                                root.set-screen-timeout(round(timeout-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.scan-duration : Rectangle {
            init => {
                smart-glasses-scan-duration-slider.value = root.get-smart-glasses-scan-duration();
                remote-id-scan-duration-slider.value = root.get-remote-id-scan-duration();
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Scan Duration";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text { text: "Smart Glasses"; color: white; }
                        Text {
                            text: round(smart-glasses-scan-duration-slider.value) + " secs";
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    smart-glasses-scan-duration-slider := Slider{
                        value: 15;
                        minimum: 15;
                        maximum: 300;

                        changed(value) => {
                            self.value = round(value/15.0) * 15;
                        }
                    }
                    HorizontalLayout {
                        Text { text: "Remote Id"; color: white; }
                        Text {
                            text: round(remote-id-scan-duration-slider.value) + " secs";
                            color: white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    remote-id-scan-duration-slider := Slider{
                        value: 15;
                        minimum:15;
                        maximum: 300;

                        changed(value) => {
                            self.value = round(value/15.0) * 15;
                        }
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-smart-glasses-scan-duration(round(smart-glasses-scan-duration-slider.value));
                                root.set-remote-id-scan-duration(round(remote-id-scan-duration-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
    }
}
