import { ScrollView, Slider } from "std-widgets.slint";
import { BatteryIndicator } from "battery-indicator.slint";
import { ImageButton } from "image-button.slint";
import { TextButton } from "text-button.slint";
import { Checkbox } from "checkbox.slint";

import "../resources/fonts/SF-Pro-Rounded-Regular.otf";

export enum SmartGlassesScanTaskCommand {
    start,
    stop
}

export enum SmartGlassesScanTaskState {
    running,
    stopped
}

export enum RemoteIdScanTaskCommand {
    start,
    stop
}

export enum RemoteIdScanTaskState {
    running,
    stopped
}

enum SettingsView {
    none,
    date,
    timezone,
    time,
    clock,
    screen,
    scan-duration
}

export component MainWindow inherits Window {
    out property <bool> showing-settings: false;
    out property <bool> showing-flashlight: false;
    in property <bool> remote-id-detected: false;
    in property <bool> smart-glasses-detected: false;
    in property <RemoteIdScanTaskState> remote-id-scan-task-state: RemoteIdScanTaskState.stopped;
    in property <SmartGlassesScanTaskState> smart-glasses-scan-task-state: SmartGlassesScanTaskState.stopped;
    in-out property <bool> clock-twelve-hour: false;
    in-out property <bool> dark-mode: false;

    pure callback set-date(month: int, day: int, year: int);
    pure callback get-date() -> [int]; // Day, month, years
    pure callback set-time(hour: int, minute: int, second: int);
    pure callback get-time() -> [int]; // Hour, minute, second
    pure callback set-timezone-offset(offset: int);
    pure callback get-timezone-offset() -> int;
    pure callback set-clock-twelve-hour(clock-twelve-hour: bool);
    pure callback get-clock-twelve-hour() -> bool;
    pure callback get-days-in-year-month(year: int, month: int) -> int;
    pure callback set-screen-brightness(brightness: int);
    pure callback get-screen-brightness() -> int;
    pure callback set-screen-timeout(timeout: int);
    pure callback get-screen-timeout() -> int;
    pure callback set-display-dark-mode(dark-mode: bool);
    pure callback get-display-dark-mode() -> bool;
    pure callback set-smart-glasses-scan-duration(duration: int);
    pure callback get-smart-glasses-scan-duration() -> int;
    pure callback set-remote-id-scan-duration(duration: int);
    pure callback get-remote-id-scan-duration() -> int;
    pure callback set-remote-id-scan-task-command(command: RemoteIdScanTaskCommand);
    pure callback set-smart-glasses-scan-task-command(command: SmartGlassesScanTaskCommand);
    callback update-datetime(hour: int, minute: int, second: int, day: int, month: int, year: int, day-of-week: int);
    callback update-battery-status(percent-charged: int, is-charging: bool);
    pure callback set-flashlight-on(bool);

    update-datetime(hour, minute, second, day, month, year, day-of-week) => {
        watch-view.hour = hour;
        watch-view.minute = minute;
        watch-view.second = second;
        watch-view.day = day;
        watch-view.month = month;
        watch-view.year = year;
        watch-view.day-of-week = day-of-week;
    }

    update-battery-status(percent-charged, is-charging) => {
        battery-indicator.value = percent-charged;
        battery-indicator.charging = is-charging;
    }

    width: 410px;
    height: 502px;
    background: black;
    default-font-family: "SF Pro Rounded";
    default-font-size: 32px;

    watch-view := Rectangle {
        property <int> hour: 0;
        property <int> minute: 0;
        property <int> second: 0;
        property <int> day: 0;
        property <int> month: 0;
        property <int> year: 0;
        property <int> day-of-week: 0;

        SwipeGestureHandler {
            VerticalLayout {
                Rectangle {
                    HorizontalLayout {
                        ImageButton {
                            icon: @image-url("../resources/icons/material-symbols--speed-camera-outline-rounded.png");
                            icon-size: 64px;
                            dark-mode: root.dark-mode;
                        }
                        ImageButton {
                            icon: @image-url("../resources/icons/material-symbols--eyeglasses-2-rounded.png");
                            icon-size: 64px;
                            dark-mode: root.dark-mode;

                            clicked => {
                                root.set-smart-glasses-scan-task-command(root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.stopped ? SmartGlassesScanTaskCommand.start : SmartGlassesScanTaskCommand.stop);
                            }

                            states [
                                detected when root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.running  && root.smart-glasses-detected: {
                                    activated: true;
                                }
                                running when root.smart-glasses-scan-task-state == SmartGlassesScanTaskState.running && !root.smart-glasses-detected: {
                                    running: true;
                                }
                            ]
                        }
                        ImageButton {
                            icon: @image-url("../resources/icons/material-symbols--drone-outline-rounded.png");
                            icon-size: 64px;
                            dark-mode: root.dark-mode;

                            clicked => {
                                root.set-remote-id-scan-task-command(root.remote-id-scan-task-state == RemoteIdScanTaskState.stopped ? RemoteIdScanTaskCommand.start : RemoteIdScanTaskCommand.stop);
                            }

                            states [
                                detected when root.remote-id-scan-task-state == RemoteIdScanTaskState.running  && root.remote-id-detected: {
                                    activated: true;
                                }
                                running when root.remote-id-scan-task-state == RemoteIdScanTaskState.running && !root.remote-id-detected: {
                                    running: true;
                                }
                            ]
                        }

                        padding: 32px;
                    }
                    
                    height: parent.height / 3;
                }
                Rectangle {
                    VerticalLayout {
                        Text {
                            text: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][day-of-week];
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: bottom;
                            horizontal-alignment: center;
                        }
                        HorizontalLayout {
                            Rectangle {}
                            Text {
                                text: (hour < 10 ? "0" : "") + (root.clock-twelve-hour ? (hour > 12 ? hour - 12 : hour) : hour);
                                color: root.dark-mode ? red : white;
                                font-size: 72px;
                                font-weight: FontWeight.black;
                                vertical-alignment: bottom;
                                horizontal-alignment: right;
                                width: 90px;
                            }
                            Text {
                                text: ":";
                                color: root.dark-mode ? red : white;
                                font-size: 72px;
                                font-weight: FontWeight.black;
                                vertical-alignment: bottom;
                                horizontal-alignment: center;
                            }
                            Text {
                                text: (minute < 10 ? "0" : "") + minute;
                                color: root.dark-mode ? red : white;
                                font-size: 72px;
                                font-weight: FontWeight.black;
                                vertical-alignment: bottom;
                                horizontal-alignment: center;
                                width: 88px;
                            }
                            Text {
                                text: ":";
                                color: root.dark-mode ? red : white;
                                font-size: 72px;
                                font-weight: FontWeight.black;
                                vertical-alignment: bottom;
                                horizontal-alignment: center;
                            }
                            Text {
                                text: (second < 10 ? "0" : "") + second;
                                color: root.dark-mode ? red : white;
                                font-size: 72px;
                                font-weight: FontWeight.black;
                                vertical-alignment: bottom;
                                horizontal-alignment: left;
                                width: 88px;
                            }
                            Rectangle {}
                        }
                        Text {
                            text: (month < 10 ? "0" : "") + month + "-" + (day < 10 ? "0" : "") + day + "-" + (year < 10 ? "0" : "") + year;
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: center;
                        }
                    }

                    height: parent.height / 3;
                }
                battery-indicator := BatteryIndicator {
                    icon-size: 64px;
                    dark-mode: root.dark-mode;
                }
            }

            swiped => {
                if self.current-position.x > self.pressed-position.x + self.width / 4 {
                    showing-flashlight = true;
                } else if self.current-position.x < self.pressed-position.x - self.width / 4 {
                    showing-settings = true;
                }
            }

            handle-swipe-right: true;
            handle-swipe-left: true;
        }
    }

    if showing-flashlight : Rectangle {
        init => {
            root.set-flashlight-on(true);
        }

        SwipeGestureHandler {
            Rectangle {
                background: root.dark-mode ? red : white;
            }

            swiped => {
                showing-flashlight = false;

                root.set-flashlight-on(false);
            }

            handle-swipe-left: true;
        }
    }

    if showing-settings : settings-container := Rectangle {
        property <SettingsView> showing-settings-view: SettingsView.none;

        settings-view := Rectangle {
            VerticalLayout {
                SwipeGestureHandler {
                    Flickable {
                        VerticalLayout {
                            TextButton {
                                height: 96px;
                                text: "Date";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.date; }
                            }
                            TextButton {
                                height: 96px;
                                text: "Time";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.time; }
                            }
                            TextButton {
                                height: 96px;
                                text: "Timezone";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.timezone; }
                            }
                            TextButton {
                                height: 96px;
                                text: "Clock";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.clock; }
                            }
                            TextButton {
                                height: 96px;
                                text: "Screen";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.screen; }
                            }
                            TextButton {
                                height: 96px;
                                text: "Scan Duration";
                                color: root.dark-mode ? red : white;

                                clicked => { showing-settings-view = SettingsView.scan-duration; }
                            }
                        }
                    }
                    swiped => {
                        root.showing-settings = false;
                    }

                    handle-swipe-right: true;
                }
            }

            background: black;
            visible: root.showing-settings;
        }

        if showing-settings-view == SettingsView.date : Rectangle {
            function update-days-in-month(year: int, month: int) {
                day-slider.maximum = root.get-days-in-year-month(year, month);

                if day-slider.value > day-slider.maximum { day-slider.value = day-slider.maximum };
            }

            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Date";
                        color: root.dark-mode ? red : white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "Year";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(year-slider.value);
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    year-slider := Slider{
                        value: root.get-date()[2];
                        minimum: 2025;
                        maximum: 2050;

                        changed(_) => {
                            update-days-in-month(year-slider.value, month-slider.value);
                        }
                    }
                    HorizontalLayout {
                        Text {
                            text: "Month";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][month-slider.value -1];
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    month-slider := Slider{
                        value: root.get-date()[1];
                        minimum: 1;
                        maximum: 12;

                        changed(_) => {
                            update-days-in-month(round(year-slider.value), round(month-slider.value));
                        }
                    }
                    HorizontalLayout {
                        Text {
                            text: "Day";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(day-slider.value);
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    day-slider := Slider{
                        value: root.get-date()[0];
                        minimum: 1;
                        maximum: root.get-days-in-year-month(year-slider.value, month-slider.value);
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            color: root.dark-mode ? red : white;

                            clicked => {
                                root.set-date(round(month-slider.value), round(day-slider.value), round(year-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.timezone : Rectangle {
            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Timezone";
                        color: root.dark-mode ? red : white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "Offset";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(timezone-slider.value);
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    timezone-slider := Slider{
                        value: root.get-timezone-offset();
                        minimum: -23;
                        maximum: 23;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            color: root.dark-mode ? red : white;

                            clicked => {
                                root.set-timezone-offset(round(timezone-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }

        if showing-settings-view == SettingsView.time : Rectangle {
            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Time";
                        color: root.dark-mode ? red : white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "Hour";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: root.clock-twelve-hour ? (round(hour-slider.value) > 12 ? round(hour-slider.value) - 12 : round(hour-slider.value)) : round(hour-slider.value);
                            color: root.dark-mode ? red : white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    hour-slider := Slider {
                        value: root.get-time()[0];
                        minimum: root.clock-twelve-hour ? 1 : 0;
                        maximum: root.clock-twelve-hour ? 24 : 23;
                    }
                    HorizontalLayout {
                        Text {
                            text: "Minute";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(minute-slider.value);
                            color: root.dark-mode ? red : white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    minute-slider := Slider {
                        value: root.get-time()[1];
                        minimum: 0;
                        maximum: 59;
                    }
                    HorizontalLayout {
                        Text {
                            text: "Second";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(second-slider.value);
                            color: root.dark-mode ? red : white;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    second-slider := Slider {
                        value: root.get-time()[2];
                        minimum: 0;
                        maximum: 59;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            color: root.dark-mode ? red : white;

                            clicked => {
                                root.set-time(round(hour-slider.value), round(minute-slider.value), round(second-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }

        if showing-settings-view == SettingsView.clock : Rectangle {
            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Clock";
                        color: white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "12-Hour";
                            color: root.dark-mode ? red : white;
                        }
                        clock-twelve-hour-checkbox := Checkbox {
                            checked: root.get-clock-twelve-hour();
                            dark-mode: root.dark-mode;
                        }
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            color: root.dark-mode ? red : white;

                            clicked => {
                                root.set-clock-twelve-hour(clock-twelve-hour-checkbox.checked);
                                root.clock-twelve-hour = clock-twelve-hour-checkbox.checked;
                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.screen : Rectangle {
            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Screen";
                        color: root.dark-mode ? red : white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "Brightness";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(brightness-slider.value) + "%";
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    brightness-slider := Slider{
                        value: round(((root.get-screen-brightness() - 16) / (255 - 16) * brightness-slider.maximum) / 10) * 10;
                        minimum: 1;
                        maximum: 100;

                        changed(value) => {
                            self.value = round(value/10.0) * 10;
                        }
                    }
                    HorizontalLayout {
                        Text {
                            text: "Timeout";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: timeout-slider.value > 0 ? round(timeout-slider.value) + " secs" : "Off";
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    timeout-slider := Slider{
                        value: root.get-screen-timeout();
                        minimum: 0;
                        maximum: 60;

                        changed(value) => {
                            self.value = round(value/5.0) * 5;
                        }
                    }
                    HorizontalLayout {
                        Text {
                            text: "Dark Mode";
                            color: root.dark-mode ? red : white;
                        }
                        dark-mode-checkbox := Checkbox {
                            checked: root.get-display-dark-mode();
                            dark-mode: root.dark-mode;
                        }
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            color: root.dark-mode ? red : white;
                            clicked => {
                                // ((0 + 25)/100) * 255
                                root.set-screen-brightness((brightness-slider.value / brightness-slider.maximum) * (255 - 16) + 16);
                                root.set-screen-timeout(round(timeout-slider.value));
                                root.set-display-dark-mode(dark-mode-checkbox.checked);
                                root.dark-mode = dark-mode-checkbox.checked;

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
        
        if showing-settings-view == SettingsView.scan-duration : Rectangle {
            TouchArea {
                VerticalLayout {
                    Text {
                        text: "Scan Duration";
                        color: root.dark-mode ? red : white;
                        font-size: 48px;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                    Rectangle {}
                    HorizontalLayout {
                        Text {
                            text: "Smart Glasses";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(smart-glasses-scan-duration-slider.value) + " secs";
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    smart-glasses-scan-duration-slider := Slider{
                        value: root.get-smart-glasses-scan-duration();
                        minimum: 15;
                        maximum: 300;

                        changed(value) => {
                            self.value = round(value/15.0) * 15;
                        }
                    }
                    HorizontalLayout {
                        Text {
                            text: "Remote Id";
                            color: root.dark-mode ? red : white;
                        }
                        Text {
                            text: round(remote-id-scan-duration-slider.value) + " secs";
                            color: root.dark-mode ? red : white;
                            font-size: 32px;
                            vertical-alignment: top;
                            horizontal-alignment: right;
                        }
                    }
                    remote-id-scan-duration-slider := Slider{
                        value: root.get-remote-id-scan-duration();
                        minimum:15;
                        maximum: 300;

                        changed(value) => {
                            self.value = round(value/15.0) * 15;
                        }
                    }
                    Rectangle {}
                    HorizontalLayout {
                        TextButton {
                            text: "Cancel";
                            color: red;
                            clicked => { showing-settings-view = SettingsView.none; }
                        }
                        TextButton {
                            text: "Done";
                            clicked => {
                                root.set-smart-glasses-scan-duration(round(smart-glasses-scan-duration-slider.value));
                                root.set-remote-id-scan-duration(round(remote-id-scan-duration-slider.value));

                                showing-settings-view = SettingsView.none;
                            }
                        }
                    }

                    spacing: 16px;
                    padding: 32px;
                }
            }

            background: black;
        }
    }
}
