export component BatteryIndicator inherits Rectangle {
    in-out property <int> value: 50;
    in-out property <bool> charging: false;
    property <image> icon;
    in property <length> icon-size: 16px;
    in property <bool> dark-mode: false;

    icon := Image {
        source: root.icon;
        width: root.icon-size;
        height: root.icon-size;
    }

    states [
        charging when charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-charging-50-2-rounded.png");
            icon.colorize: dark-mode ? red : white;
        }
        full when value >= 90 && !charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-horiz-100-rounded.png");
            icon.colorize: dark-mode ? red : white;
        }
        two-thirds when value < 90 && value > 75 && !charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-horiz-075-rounded.png");
            icon.colorize: dark-mode ? red : white;
        }
        half when value <= 75 && value > 50 && !charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-horiz-050-rounded.png");
            icon.colorize: dark-mode ? red : white;
        }
        one-third when value <= 50 && value > 25 && !charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-horiz-025-rounded.png");
            icon.colorize: dark-mode ? red : white;
        }
        empty when value <= 25 && !charging: {
            icon: @image-url("../resources/icons/material-symbols--battery-horiz-000-rounded.png");
            icon.colorize: dark-mode ? yellow : red;
        }
    ]
}