export component ImageButton inherits TouchArea {
    in property <image> icon;
    in property <length> icon-size: 16px;
    in-out property <bool> running: false;
    in-out property <bool> activated: false;

    icon := Image {
        source: root.icon;
        width: root.icon-size;
        height: root.icon-size;
        image-fit: contain;

        animate colorize {
            duration: 100ms;
        }
    }

    states [  
        pressed when root.pressed: {
            icon.colorize: #808080;
        }

        activated when activated: {
            icon.colorize: #ff0000;
        }

        running when running: {
            icon.colorize: #00ff00;
        }
    ]
}