export component ImageButton inherits TouchArea {
    in property <image> icon;
    in property <length> icon-size: 64px;
    in-out property <bool> running: false;
    in-out property <bool> activated: false;
    in property <bool> dark-mode: false;

    icon := Image {
        source: root.icon;
        width: root.icon-size;
        height: root.icon-size;
        image-fit: contain;
        colorize: dark-mode ? red : white;
    }

    states [
        disabled when !self.enabled: {
            icon.colorize: #808080;
        }

        pressed when root.pressed: {
            icon.colorize: #808080;
        }

        activated when activated: {
            icon.colorize: dark-mode ? yellow : red;
        }

        running when running: {
            icon.colorize: green;
        }
    ]
}